name: Build wheels, tag and publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag_release:
    name: Create git tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - uses: actions/checkout@v5

      - name: Read version from setup.py
        id: get_version
        run: |
          version=$(sed -n 's/.*version="\([0-9.]*\)".*/\1/p' setup.py)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "tag=v$version" >> "$GITHUB_OUTPUT"

      - name: Create and push git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.get_version.outputs.tag }}"
          git push origin "${{ steps.get_version.outputs.tag }}"

  build_wheels:
    name: Build wheels on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: "ubuntu-24.04"
          - name: "ubuntu-24.04-arm"
          - name: "macos-14"
          - name: "windows-20255"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          # Native architectures only
          CIBW_ARCHS_LINUX: auto
          CIBW_ARCHS_MACOS: auto
          CIBW_ARCHS_WINDOWS: auto
          # Skip PyPy and free-threaded builds
          CIBW_SKIP: "pp* *t-*"
          # Skip tests
          CIBW_TEST_SKIP: "*"
          # More verbose logs
          CIBW_BUILD_VERBOSITY: 3

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os.name }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Create release and publish to PyPI
    needs: [tag_release, build_wheels]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Twine
        run: |
          pip install twine
          cd dist && for i in $(ls); do mv ${i}/*.whl .; rmdir ${i}; done && cd ..

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*.whl"
          tag: ${{ needs.tag_release.outputs.tag }}
          name: ${{ needs.tag_release.outputs.tag }}
          commit: ${{ github.sha }}

      - name: Publish wheels to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
